// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package annotations

import (
	"database/sql"
)

type Annotation struct {
	ID        int64
	Filename  string
	Keyword   string
	Content   string
	Notes     sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
